test retry build

diff --git a/build b/build
--- a/build
+++ b/build
@@ -93,10 +93,15 @@ echo "Run sbuild"
 
 # Don't build tests
 export DEB_BUILD_OPTIONS=nocheck
+DONE=false
+# while not done
+TRIES=0
 
+while [ -z "$DONE" ]; do
+TRIES=$((TRIES+1))
 TOTAL="$( (catkin_topological_order --only-names || colcon list --topological-order --names-only) | wc -l)"
 COUNT=1
-
+FCOUNT=0
 test -n "$DEB_ARCH" && set -- --arch="$DEB_ARCH" "$@"
 
 for PKG_PATH in $(catkin_topological_order --only-folders || colcon list --topological-order --paths-only); do
@@ -118,8 +123,11 @@ for PKG_PATH in $(catkin_topological_order --only-folders || colcon list --topol
     exit
   fi
 
-  ROS_HOME="$APT_REPO/ros" BLOOM_SKIP_ROSDEP_UPDATE=1 bloom-generate "${BLOOM}debian" --os-name="$DISTRIBUTION" --os-version="$DEB_DISTRO" --ros-distro="$ROS_DISTRO" || true
-
+  ROS_HOME="$APT_REPO/ros" BLOOM_SKIP_ROSDEP_UPDATE=1 bloom-generate "${BLOOM}debian" --os-name="$DISTRIBUTION" --os-version="$DEB_DISTRO" --ros-distro="$ROS_DISTRO" || (FAILED=true; true)
+  if [ -n "$FAILED" ]; then
+    echo "Failed to generate package for $ROS_PACKAGE"
+    FCOUNT=$((FCOUNT+1))
+  fi
   # Set the version based on the checked out tag that contain at least on digit
   # strip any leading non digits as they are not part of the version number
   sed -i "1 s@([^)]*)@($( (git describe --tag  --match "*[0-9]*" 2>/dev/null || echo 0) | sed -e 's@^[^0-9]*@@' -e 's@_@~@g')-$(date +%Y.%m.%d.%H.%M))@" debian/changelog
@@ -139,7 +147,16 @@ for PKG_PATH in $(catkin_topological_order --only-folders || colcon list --topol
   COUNT=$((COUNT+1))
   echo "::endgroup::"
 done
-
+echo "Failed to generate $FCOUNT packages"
+# done if all packages are built
+if [ "$FCOUNT" -eq 0 ]; then
+  DONE=true
+fi
+if [ "$TRIES" -gt 2 ]; then
+  echo "Retrying failed packages too often"
+  DONE=true
+fi
+done
 rm -r "$APT_REPO/ros"
 
 ccache -sv
